server:
    port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

build:
 version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Aman Singh- Developer"
    email: "aman@eazybank.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345
